<?php
//OpenCEX upgrades
return ["INSERT INTO Misc (Kei, Val) VALUES ('testupgradesuccess', '1');",
"CREATE TABLE IF NOT EXISTS WorkerTasks (Id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, URL VARCHAR(255), LastTouched BIGINT, Status BIT);",
"ALTER TABLE WorkerTasks ADD URL2 VARCHAR(255) NOT NULL;",
"ALTER TABLE WorkerTasks MODIFY COLUMN URL VARCHAR(255) NOT NULL"];
?>